[workspace]
resolver = "3"
members = ["packages/binance-api-cli", "packages/binance-api-rest"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.93.1"
homepage = "https://github.com/DenisGorbachev/binance-api"
repository = "https://github.com/DenisGorbachev/binance-api"
keywords = []
categories = []
exclude = [
    ".*",
    "*.local.*",
    "doc/dev",
    "specs",
    "AGENTS.ts",
    "CargoMetadata.ts",
    "README.ts",
    "AGENTS*.md",
    "CLAUDE*.md",
    "deno.lock",
    "deno.json",
    "commitlint.config.mjs",
    "fnox.toml",
    "mise.toml",
    "rumdl.toml",
    "rustfmt.toml",
    ".yolobox"
]

[workspace.metadata.details]
name = "binance-api"
title = ""
readme = { generate = false }

[workspace.lints.rust]
redundant_imports = "deny"
unused_import_braces = "deny"
# unused_qualifications must not be "deny" because our code style has multiple `use Foo::*;`, and some macros (derive_more::Display, strum::Display, strum::EnumString) produce code with full qualifications
# unused_qualifications = "deny"

[workspace.lints.clippy]
absolute_paths = "deny"
arithmetic_side_effects = "deny"

[workspace.dependencies]
derive-getters = { version = "0.5.0", features = ["auto_copy_getters"] }
derive-new = "0.7.0"
derive_more = { version = "2.1.1", features = ["full"] }
errgonomic = { git = "https://github.com/DenisGorbachev/errgonomic" }
itertools = "0.15.0"
standard-traits = { git = "https://github.com/DenisGorbachev/standard-traits" }
strum = { version = "0.28.0", features = ["derive"] }
stub-macro = { version = "0.3.1" }
subtype = { git = "https://github.com/DenisGorbachev/subtype" }
rust_decimal = "1.42.1"
timestamp-please = { git = "https://github.com/DenisGorbachev/timestamp-please" }
